### ISSUE TITLE
Getting error while just using the package method: ReferenceError: Window is not defined 

### ISSUE THREAD

**Issue by shreyasmeva** [mahmoudshahin1111/numbers-to-arabic-words#10]
I just try running this command and it returned error.

```
var numberToArabicWords = require("number-to-arabic-words");
console.log(numberToArabicWords.toArabicWord(1000));
```

![image](https://user-images.githubusercontent.com/80309702/196147798-cf88575b-3d8a-43fd-8165-44909dc8fbb7.png)

**Comment by mahmoudshahin1111** [comment]
Hi @shreyasmeva as documented here https://github.com/mahmoudshahin1111/numbers-to-arabic-words#nodejs if you are going to use it in Nodejs you should do it like this by selecting the Nodejs file `index-node.js`
```js
const NumbersToArabicWords = require('dist/index-node.js')
NumbersToArabicWords.toArabicWord(1000)
```

**Comment by shreyasmeva** [comment]
Hello @mahmoudshahin1111 , Founf the solution useful. Seems this package has not same definition as usually all package uses.
Still going this way do not raises any issue.

Functionality seems working best.

Thanks for the help.
